import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./admin/style.css";

// Font optimization with display swap for better performance
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

// Advanced Viewport configuration (Next.js 14+)
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0f172a" },
  ],
  width: "device-width",
  initialScale: 1,
};

// Advanced SEO Metadata
export const metadata: Metadata = {
  title: {
    default: "My App | Home",
    template: "%s | My App", // Baaki pages ke liye automatic title formatting
  },
  description: "Generated by create next app, built with Next.js and Tailwind CSS",
  keywords: ["Next.js", "React", "Tailwind CSS", "JavaScript", "TypeScript"],
  authors: [{ name: "Your Name" }],
  creator: "Your Name",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://yourwebsite.com",
    title: "My App",
    description: "Generated by create next app",
    siteName: "My App",
  },
  twitter: {
    card: "summary_large_image",
    title: "My App",
    description: "Generated by create next app",
  },
  robots: {
    index: true,
    follow: true,
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    /* suppressHydrationWarning HTML class extensions ( jaise next-themes) ki wajah se warning aane se rokta hai */
    <html 
      lang="en" 
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-foreground selection:bg-primary selection:text-primary-foreground">
        {/* Agar aapko global header ya footer lagana ho toh yahan wrap kar sakte hain */}
        <main className="flex-1 flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}