import { NextResponse } from "next/server";
import {
  createHmac,
  randomBytes,
  scrypt as scryptCallback,
  timingSafeEqual,
} from "node:crypto";
import { promisify } from "node:util";
import {
  Document,
  MongoClient,
} from "mongodb";

export const runtime = "nodejs";

const scrypt = promisify(scryptCallback);

const SESSION_COOKIE_NAME = "hcs-session";
const SESSION_TTL_SECONDS = 8 * 60 * 60;

type AuthRole = "admin" | "client";

type LoginBody = {
  role?: AuthRole;
  identifier?: string;
  password?: string;
};

type SafeUser = {
  id: string;
  adminId?: string;
  clientId?: string;
  accountId?: string;
  username?: string;
  name?: string;
  fullName?: string;
  email?: string;
  companyName?: string;
  role: AuthRole;
};

type SessionPayload = {
  sub: string;
  role: AuthRole;
  iat: number;
  exp: number;
  nonce: string;
};

let mongoClientPromise: Promise<MongoClient> | null =
  null;

/* -------------------------------------------------------------------------- */
/* MongoDB                                                                    */
/* -------------------------------------------------------------------------- */

function getMongoUri(): string {
  const uri =
    process.env.MONGODB_URI?.trim();

  if (!uri) {
    throw new Error(
      "MONGODB_URI is not configured.",
    );
  }

  return uri;
}

function getDatabaseName(): string {
  const configured =
    process.env.MONGODB_DB?.trim() ||
    process.env.MONGODB_DATABASE?.trim();

  if (configured) {
    return configured;
  }

  const uri = getMongoUri();

  const withoutProtocol =
    uri.replace(
      /^mongodb(?:\+srv)?:\/\//,
      "",
    );

  const slashIndex =
    withoutProtocol.indexOf("/");

  if (slashIndex !== -1) {
    const afterSlash =
      withoutProtocol.slice(
        slashIndex + 1,
      );

    const databaseName =
      afterSlash
        .split("?")[0]
        .trim();

    if (databaseName) {
      return decodeURIComponent(
        databaseName,
      );
    }
  }

  return "hcs";
}

function getAdminCollectionName(): string {
  return (
    process.env.MONGODB_ADMIN_COLLECTION?.trim() ||
    "admins"
  );
}

function getClientCollectionName(): string {
  return (
    process.env.MONGODB_CLIENT_COLLECTION?.trim() ||
    "clients"
  );
}

async function getMongoClient(): Promise<MongoClient> {
  if (!mongoClientPromise) {
    const client =
      new MongoClient(
        getMongoUri(),
        {
          maxPoolSize: 10,
          minPoolSize: 0,
          serverSelectionTimeoutMS: 10_000,
        },
      );

    mongoClientPromise =
      client.connect();
  }

  return mongoClientPromise;
}

/* -------------------------------------------------------------------------- */
/* Security                                                                    */
/* -------------------------------------------------------------------------- */

function getSessionSecret(): string {
  const secret =
    process.env.HCS_SESSION_SECRET?.trim();

  if (!secret) {
    throw new Error(
      "HCS_SESSION_SECRET is not configured.",
    );
  }

  if (secret.length < 32) {
    throw new Error(
      "HCS_SESSION_SECRET must contain at least 32 characters.",
    );
  }

  return secret;
}

function safeEqual(
  a: Buffer,
  b: Buffer,
): boolean {
  if (a.length !== b.length) {
    return false;
  }

  return timingSafeEqual(a, b);
}

async function verifyPassword(
  password: string,
  storedHash: unknown,
): Promise<boolean> {
  if (
    typeof storedHash !== "string" ||
    !storedHash
  ) {
    return false;
  }

  /*
   * Expected format:
   *
   * scrypt:<salt>:<derived-key-hex>
   *
   * This matches the password hash generated by
   * the reset-password API.
   */
  const parts =
    storedHash.split(":");

  if (
    parts.length !== 3 ||
    parts[0] !== "scrypt"
  ) {
    return false;
  }

  const [, salt, storedKeyHex] =
    parts;

  if (
    !salt ||
    !storedKeyHex ||
    !/^[0-9a-f]+$/i.test(
      storedKeyHex,
    )
  ) {
    return false;
  }

  let storedKey: Buffer;

  try {
    storedKey =
      Buffer.from(
        storedKeyHex,
        "hex",
      );
  } catch {
    return false;
  }

  if (!storedKey.length) {
    return false;
  }

  const derivedKey =
    (await scrypt(
      password,
      salt,
      storedKey.length,
    )) as Buffer;

  return safeEqual(
    derivedKey,
    storedKey,
  );
}

function escapeRegex(
  value: string,
): string {
  return value.replace(
    /[.*+?^${}()|[\]\\]/g,
    "\\$&",
  );
}

/* -------------------------------------------------------------------------- */
/* Identifier helpers                                                          */
/* -------------------------------------------------------------------------- */

function normalizeEmail(
  value: string,
): string {
  return value
    .trim()
    .toLowerCase();
}

function normalizeGeneralIdentifier(
  value: string,
): string {
  return value
    .trim()
    .toLowerCase();
}

/* -------------------------------------------------------------------------- */
/* Session                                                                     */
/* -------------------------------------------------------------------------- */

function encodeSession(
  payload: SessionPayload,
): string {
  const encoded =
    Buffer.from(
      JSON.stringify(payload),
    ).toString(
      "base64url",
    );

  const signature =
    createHmac(
      "sha256",
      getSessionSecret(),
    )
      .update(encoded)
      .digest("base64url");

  return `${encoded}.${signature}`;
}

/* -------------------------------------------------------------------------- */
/* Same-origin protection                                                      */
/* -------------------------------------------------------------------------- */

function validateSameOrigin(
  request: Request,
): boolean {
  const origin =
    request.headers.get("origin");

  if (!origin) {
    return true;
  }

  try {
    return (
      new URL(origin).origin ===
      new URL(request.url).origin
    );
  } catch {
    return false;
  }
}

/* -------------------------------------------------------------------------- */
/* Admin lookup                                                                */
/* -------------------------------------------------------------------------- */

async function findAdmin(
  identifier: string,
) {
  const client =
    await getMongoClient();

  const db =
    client.db(
      getDatabaseName(),
    );

  const collection =
    db.collection(
      getAdminCollectionName(),
    );

  const normalized =
    normalizeGeneralIdentifier(
      identifier,
    );

  if (
    !normalized
  ) {
    return null;
  }

  return collection.findOne({
    $or: [
      {
        adminId: {
          $regex: `^${escapeRegex(
            normalized,
          )}$`,
          $options: "i",
        },
      },
      {
        username: {
          $regex: `^${escapeRegex(
            normalized,
          )}$`,
          $options: "i",
        },
      },
      {
        email: {
          $regex: `^${escapeRegex(
            normalizeEmail(
              identifier,
            ),
          )}$`,
          $options: "i",
        },
      },
    ],
  });
}

/* -------------------------------------------------------------------------- */
/* Client lookup                                                               */
/* -------------------------------------------------------------------------- */

async function findClient(
  identifier: string,
) {
  const client =
    await getMongoClient();

  const db =
    client.db(
      getDatabaseName(),
    );

  const collection =
    db.collection(
      getClientCollectionName(),
    );

  const normalized =
    normalizeGeneralIdentifier(
      identifier,
    );

  if (
    !normalized
  ) {
    return null;
  }

  return collection.findOne({
    $or: [
      {
        clientId: {
          $regex: `^${escapeRegex(
            normalized,
          )}$`,
          $options: "i",
        },
      },
      {
        username: {
          $regex: `^${escapeRegex(
            normalized,
          )}$`,
          $options: "i",
        },
      },
      {
        email: {
          $regex: `^${escapeRegex(
            normalizeEmail(
              identifier,
            ),
          )}$`,
          $options: "i",
        },
      },
    ],
  });
}

/* -------------------------------------------------------------------------- */
/* Safe user objects                                                           */
/* -------------------------------------------------------------------------- */

function adminToSafeUser(
  admin: Document,
): SafeUser {
  const id =
    String(
      admin._id ?? admin.adminId ?? "",
    );

  return {
    id,
    adminId:
      admin.adminId
        ? String(admin.adminId)
        : undefined,
    accountId:
      admin._id
        ? String(admin._id)
        : admin.adminId
          ? String(admin.adminId)
          : undefined,
    username:
      admin.username
        ? String(admin.username)
        : undefined,
    name:
      admin.fullName
        ? String(admin.fullName)
        : admin.name
          ? String(admin.name)
          : "HCS Administrator",
    fullName:
      admin.fullName
        ? String(admin.fullName)
        : undefined,
    email:
      admin.email
        ? String(admin.email)
        : undefined,
    role: "admin",
  };
}

function clientToSafeUser(
  client: Document,
): SafeUser {
  const id =
    String(
      client._id ??
        client.clientId ??
        "",
    );

  return {
    id,
    clientId:
      client.clientId
        ? String(client.clientId)
        : undefined,
    accountId:
      client._id
        ? String(client._id)
        : client.clientId
          ? String(client.clientId)
          : undefined,
    username:
      client.username
        ? String(client.username)
        : undefined,
    name:
      client.name
        ? String(client.name)
        : client.companyName
          ? String(client.companyName)
          : "Client",
    email:
      client.email
        ? String(client.email)
        : undefined,
    companyName:
      client.companyName
        ? String(client.companyName)
        : "",
    role: "client",
  };
}

/* -------------------------------------------------------------------------- */
/* POST                                                                        */
/* -------------------------------------------------------------------------- */

export async function POST(
  request: Request,
) {
  try {
    if (!validateSameOrigin(request)) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Invalid request origin.",
        },
        {
          status: 403,
        },
      );
    }

    let body: LoginBody;

    try {
      body =
        (await request.json()) as LoginBody;
    } catch {
      return NextResponse.json(
        {
          success: false,
          message:
            "Invalid request body.",
        },
        {
          status: 400,
        },
      );
    }

    const role =
      body.role;

    const identifier =
      body.identifier?.trim() ?? "";

    const password =
      body.password ?? "";

    if (
      role !== "admin" &&
      role !== "client"
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Invalid account type.",
        },
        {
          status: 400,
        },
      );
    }

    if (
      !identifier ||
      !password
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Username/email and password are required.",
        },
        {
          status: 400,
        },
      );
    }

    /*
     * Hard upper bound prevents unnecessarily large
     * password input from reaching scrypt.
     */
    if (
      password.length > 128
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Invalid credentials.",
        },
        {
          status: 401,
        },
      );
    }

    let account:
      | Document
      | null = null;

    if (role === "admin") {
      account =
        await findAdmin(
          identifier,
        );
    } else {
      account =
        await findClient(
          identifier,
        );
    }

    /*
     * Do not reveal whether the account exists.
     */
    if (!account) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Invalid credentials.",
        },
        {
          status: 401,
        },
      );
    }

    if (
      account.active === false
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            role === "admin"
              ? "Administrator account is inactive."
              : "Client account is inactive.",
        },
        {
          status: 403,
        },
      );
    }

    if (
      role === "client" &&
      (
        account.status === "Suspended" ||
        account.status === "Disabled" ||
        account.clientPortalEnabled === false
      )
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Client account is unavailable.",
        },
        {
          status: 403,
        },
      );
    }

    const passwordHash =
      account.passwordHash;

    const passwordValid =
      await verifyPassword(
        password,
        passwordHash,
      );

    if (!passwordValid) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Invalid credentials.",
        },
        {
          status: 401,
        },
      );
    }

    const now =
      Math.floor(
        Date.now() / 1000,
      );

    const subject =
      String(
        account._id ??
          account.adminId ??
          account.clientId ??
          "",
      );

    if (!subject) {
      console.error(
        "HCS login error: Account has no stable ID.",
      );

      return NextResponse.json(
        {
          success: false,
          message:
            "Authentication configuration error.",
        },
        {
          status: 500,
        },
      );
    }

    const sessionPayload: SessionPayload =
      {
        sub: subject,
        role,
        iat: now,
        exp:
          now +
          SESSION_TTL_SECONDS,
        nonce:
          randomBytes(
            18,
          ).toString(
            "base64url",
          ),
      };

    const sessionToken =
      encodeSession(
        sessionPayload,
      );

    const user =
      role === "admin"
        ? adminToSafeUser(
            account,
          )
        : clientToSafeUser(
            account,
          );

    const response =
      NextResponse.json(
        {
          success: true,
          role,
          user,
        },
        {
          status: 200,
        },
      );

    response.cookies.set(
      SESSION_COOKIE_NAME,
      sessionToken,
      {
        httpOnly: true,
        secure:
          process.env.NODE_ENV ===
          "production",
        sameSite: "lax",
        path: "/",
        maxAge:
          SESSION_TTL_SECONDS,
        priority: "high",
      },
    );

    /*
     * Update last login without failing the login
     * if this non-critical write fails.
     */
    try {
      const client =
        await getMongoClient();

      const db =
        client.db(
          getDatabaseName(),
        );

      const collection =
        db.collection(
          role === "admin"
            ? getAdminCollectionName()
            : getClientCollectionName(),
        );

      const update: Document = {
        $set: {
          lastLogin:
            new Date(),
          updatedAt:
            new Date(),
        },
      };

      await collection.updateOne(
        {
          _id: account._id,
        },
        update,
      );
    } catch (lastLoginError) {
      console.error(
        "HCS login lastLogin update failed:",
        lastLoginError,
      );
    }

    return response;
  } catch (error) {
    console.error(
      "HCS login error:",
      error,
    );

    return NextResponse.json(
      {
        success: false,
        message:
          "Unable to sign in right now.",
      },
      {
        status: 500,
      },
    );
  }
}